### ISSUE TITLE
Некорректная работа сервиса оплаты при платеже, превышающем текущий баланс. 

### ISSUE THREAD

**Issue by mmpomail** [mmpomail/TeamWorkJava#2]
# Описание

При попытке совершения платежа на сумму большую, чем остаток на счёте, метод оплаты возвращает отрицательное значение остатка на счёте. 

# Локация дефекта

https://github.com/mmpomail/TeamWorkJava/blob/f384364b0367b0ac5069018bbe213f1aa612b092/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L44

# Шаги воспроизведения

1. В классе SavingAccount создать объект account с параметрами: initialBalance: 2_000, minBalance: 1_000, maxBalance: 10_000, rate: 5.
2. Вызвать метод pay с параметром 3_000.

_Ожидаемый результат:_ Значение initialBalance останется равным 2_000. 
_Фактический результат:_ Значение initialBalance изменилось на -1_000.

# Тест

https://github.com/mmpomail/TeamWorkJava/blob/f384364b0367b0ac5069018bbe213f1aa612b092/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L65

# Скриншот

![Issue 2](https://github.com/mmpomail/TeamWorkJava/assets/157794839/4ee6d547-7f7e-4c57-944f-5a2ec447423a)

# Окружение

- **Операционная система:** Windows 11.
- **IDE:** IntelliJ IDEA 2024.1 (Ultimate Edition).
- **Java:** Open JDK 11.

**Comment by Tatyanochka16** [comment]
"debug saving" commit
