### ISSUE TITLE
Не выбрасывается исключение при отрицательном минимальном балансе.

### ISSUE THREAD

**Issue by mmpomail** [mmpomail/TeamWorkJava#3]
# Описание

При установлении отрицательного числа в значение минимального баланса не выбрасывается исключение IllegalArgumentException.

# Локация дефекта

https://github.com/mmpomail/TeamWorkJava/blob/f384364b0367b0ac5069018bbe213f1aa612b092/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L22

# Шаги воспроизведения

1) В классе SavingAccount создать объект с параметрами: initialBalance: 2_000, minBalance: -1_000, maxBalance: 10_000, rate: 5.
2) Запустить тест на проверку исключения с вышеуказанным объектом.

_Ожидаемый результат:_ Выбросится исключение IllegalArgumentException.
_Фактический результат:_ Тест падает. 

# Тест

https://github.com/mmpomail/TeamWorkJava/blob/2da3e0d6c336137532b613e37f6cd4b51369cf01/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L99

# Скриншот

![Issue 3](https://github.com/mmpomail/TeamWorkJava/assets/157794839/6525d0f1-e5d9-4b1a-9219-576bfa47a546)

# Окружение

- **Операционная система:** Windows 11.

- **IDE:** IntelliJ IDEA 2024.1 (Ultimate Edition).

- **Java:** Open JDK 11.

**Comment by Tatyanochka16** [comment]
"debug saving" commit
