### ISSUE TITLE
Не выбрасывается исключение, если минимальный баланс больше максимального.

### ISSUE THREAD

**Issue by mmpomail** [mmpomail/TeamWorkJava#4]
# Описание

При установлении в параметр минимального значения большего числа, чем в параметре максимального значения не выбрасывается исключение IllegalArgumentException.

# Локация дефекта

https://github.com/mmpomail/TeamWorkJava/blob/2da3e0d6c336137532b613e37f6cd4b51369cf01/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L22

# Шаги воспроизведения

1) В классе SavingAccount создать объект с параметрами: initialBalance: 500, minBalance: 5_000, maxBalance: 1_000, rate: 5.
2) Запустить тест на проверку исключения с вышеуказанным объектом.

_Ожидаемый результат:_ Выбросится исключение IllegalArgumentException.
_Фактический результат:_ Тест падает.

# Тест

https://github.com/mmpomail/TeamWorkJava/blob/2da3e0d6c336137532b613e37f6cd4b51369cf01/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L105

# Скриншот 

![Issue 4](https://github.com/mmpomail/TeamWorkJava/assets/157794839/ce342b5d-1321-4e50-ae9a-7cf2aad6154a)

# Окружение

- **Операционная система:** Windows 11.

- **IDE:** IntelliJ IDEA 2024.1 (Ultimate Edition).

- **Java:** Open JDK 11.

**Comment by Tatyanochka16** [comment]
"debug saving" commit
