### ISSUE TITLE
Не выкидывается исключение вида IllegalArgumentException при некорректном начальном балансе

### ISSUE THREAD

**Issue by Tatyanochka16** [mmpomail/TeamWorkJava#5]
# Описание

При начальном балансе, привышающем кредитный лимит, не выкидывается исключение вида IllegalArgumentException.

# Локализация

https://github.com/mmpomail/TeamWorkJava/blob/de3ec6f0656bee809f8cd7d60188d0ac064bf0a3/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L19-L28

# Шаги воспроизведения

1. Открыть [код программы] (https://github.com/mmpomail/TeamWorkJava/blob/credit/src/main/java/ru/netology/javaqadiplom/CreditAccount.java) в IDLE;
2. Создать объект CreditAccount класса CreditAccount с начальным балансом -5_001, кредитным лимитом 5_000 и ставкой 15;
3. Вывести значение баланса объекта на экран;
4. Посмотреть на вывод в консоли.

**Ожидаемый результат**: Выкидывается исключение вида IllegalArgumentException.
**Фактический результат**: Исключение не выкидывается. Класс позволяет создать объект CreditAccount при введенном отрицательном значении баланса, превышающем кредитный лимит.

# Тест

https://github.com/mmpomail/TeamWorkJava/blob/de3ec6f0656bee809f8cd7d60188d0ac064bf0a3/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L55-L61

# Скриншот

![NegativeBalance](https://github.com/mmpomail/TeamWorkJava/assets/157831232/5edb0f54-1b1f-4c91-95d4-0664275433eb)

# Окружение

* **Операционная система:** Windows 10
* **IDE:** IntelliJ IDEA 2023.3.4 
* **Java:**  OpenJDK 11

**Comment by mmpomail** [comment]
Исправлено.
